version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2

    working_directory: ~/app
    steps:
      # git pull
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}

      - run:
          name: Setting up Docker
          command: |
            echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: Build and push to DockerHub
          command: |
            docker build --tag=aliyura/tamalin-backend:latest .
            docker push aliyura/tamalin-backend:latest
