export enum UserRole {
  ADMIN = 'ADMIN',
  AGENT = 'AGENT',
}
export enum Status {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  BLOCKED = 'BLOCKED',
  FAILED = 'FAILED',
  SUCCESSFUL = 'SUCCESSFUL',
}
export enum InstalmentPeriod {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  HALFLY = 'HALFLY',
  YEARLY = 'YEARLY',
}

export enum IdentityType {
  NIN = 'NIN',
  DRIVERLICENSE = 'DRIVERLICENSE',
  INTERNATIONALPASSPORT = 'INTERNATIONALPASSPORT',
}
